# Generated by Django 2.1.7 on 2019-05-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.AutoField(max_length=5, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=80)),
                ('author', models.CharField(max_length=15)),
                ('url', models.CharField(max_length=400)),
                ('comments', models.CharField(max_length=5)),
                ('points', models.CharField(max_length=5)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(max_length=5, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=20)),
                ('news_labeled', models.CharField(max_length=4000)),
                ('favorite', models.CharField(max_length=400)),
            ],
        ),
    ]
